services:
  - type: web
    name: tahsilat-backend
    runtime: docker
    plan: free
    rootDir: backend/tahsilat
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_SWAGGER_PUBLIC
        value: "false"
