spring.application.name=tahsilat
spring.datasource.url=jdbc:postgresql://localhost:5432/tahsilat_db
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080