spring.jpa.hibernate.ddl-auto=validate

server.error.include-message=never
server.error.include-binding-errors=never

logging.level.com.veli.tahsilat.security=WARN
logging.level.com.veli.tahsilat.auth.service.impl.AuthServiceImpl=WARN

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
app.swagger.public=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
